# image will be published to ghcr.io/<user>/<name>
name: mars
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblue/hyprland-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/bottom/repo/fedora-%OS_VERSION%/atim-bottom-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jplie/budgie-extras/repo/fedora-%OS_VERSION%/jplie-budgie-extras-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - rofi
      - fish
      - gh
      - xrandr
      - bottom
      - gnome-tweaks
      - alacritty
      - ImageMagick
      - mpv
      - neovim
      - fontawesome-fonts
      - tumbler
      - budgie-extras
      - screen
      - direnv
      - langpacks-en
      - ruff
      - uv
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      - ExtensionManager: com.mattjakeman.ExtensionManager
      - LibreOffice: org.libreoffice.LibreOffice
      - FontDownloader: org.gustavoperedo.FontDownloader
      - Flatseal: com.github.tchx84.Flatseal
      - Celluloid: io.github.celluloid_player.Celluloid
      - Obsidian: md.obsidian.Obsidian
      - Studio: io.beekeeperstudio.Studio
      - Vorta: com.borgbase.Vorta
      - Slack: com.slack.Slack
      - Chrome: com.google.Chrome
      - wezterm: org.wezfurlong.wezterm
      - Floorp: one.ablaze.floorp
      - Bitwarden: com.bitwarden.desktop
      - Todoist: com.todoist.Todoist
      - Ferdium: org.ferdium.Ferdium
      - Freetube: io.freetubeapp.FreeTube
      - Zed: dev.zed.Zed
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
  - type: chezmoi
    repository: "https://github.com/robintully/dotfiles" # my dotfiles repo
    all-users: true # make users have to enable chezmoi manually
    file-conflict-policy: replace # override changed files with those from the repo
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

