name: mars
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/aurora-dx-nvidia
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - >-
        https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - >-
        https://copr.fedorainfracloud.org/coprs/atim/bottom/repo/fedora-%OS_VERSION%/atim-bottom-fedora-%OS_VERSION%.repo
      # - >-
      #   https://copr.fedorainfracloud.org/coprs/jplie/budgie-extras/repo/fedora-%OS_VERSION%/jplie-budgie-extras-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      # - fish
      - gh
      - xrandr
      - bottom
      # - gnome-tweaks
      - alacritty
      - ImageMagick
      - mpv
      - neovim
      - fontawesome-fonts
      - tumbler
      - screen
      - direnv
      - langpacks-en
      # - swaybg
      # - cinnamon
      # - cinnamon-control-center
      # - cinnamon-screensaver
      # - cinnamon-session
      # - cinnamon-settings-daemon
      # - cinnamon-themes
      # - cinnamon-translations
      # - gnome-settings-daemon
      # - gnome-terminal
      # - file-roller
      # - evince
      # - gnome-screenshot
      # - nautilus
      - dconf-editor
      # - mutter
      # - gnome-control-center
      # - network-manager-applet
    # remove:
      # - firefox
      # - firefox-langpacks
  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.libreoffice.LibreOffice
        - org.gustavoperedo.FontDownloader
        - com.github.tchx84.Flatseal
        - io.github.celluloid_player.Celluloid
        - md.obsidian.Obsidian
        - io.beekeeperstudio.Studio
        - com.borgbase.Vorta
        - com.slack.Slack
        - com.google.Chrome
        - org.wezfurlong.wezterm
        - one.ablaze.floorp
        - com.bitwarden.desktop
        - com.todoist.Todoist
        - org.ferdium.Ferdium
        - io.freetubeapp.FreeTube
        - dev.zed.Zed
      remove: null
  - type: chezmoi
    repository: "https://github.com/robintully/dotfiles"
    all-users: true
    file-conflict-policy: replace
  - type: signing

  - type: signing
