name: mars
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: stable
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      # - >-
      #   https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - >-
        https://copr.fedorainfracloud.org/coprs/atim/bottom/repo/fedora-%OS_VERSION%/atim-bottom-fedora-%OS_VERSION%.repo
      - >-
        https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
      - >-
        https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
      - >-
        https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-%OS_VERSION%/sneexy-zen-browser-%OS_VERSION%.repo
      # - >-
      #   https://copr.fedorainfracloud.org/coprs/jplie/budgie-extras/repo/fedora-%OS_VERSION%/jplie-budgie-extras-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      # - fish
      - gh
      - xrandr
      - bottom
      # - gnome-tweaks
      - alacritty
      - ImageMagick
      - mpv
      - neovim
      - fontawesome-fonts
      - tumbler
      - screen
      - direnv
      - langpacks-en
      - pavucontrol
      - python3-devel
      - dconf-editor
      - cosmic-desktop
      - wezterm
      - zen-browser
    # remove:
      # - firefox
      # - firefox-langpacks
  - type: chezmoi
    repository: "https://github.com/robintully/dotfiles"
    all-users: true
    file-conflict-policy: replace
  - type: justfiles
    validate: false
    include:
      - kde.just
  - type: default-flatpaks
    notify: true
    user:
      repo-name: flathub
      repo-title: "Flathub (User)"
      install:
        - org.mozilla.firefox
        - org.libreoffice.LibreOffice
        - org.gustavoperedo.FontDownloader
        - com.github.tchx84.Flatseal
        - io.github.celluloid_player.Celluloid
        - md.obsidian.Obsidian
        - io.beekeeperstudio.Studio
        - com.borgbase.Vorta
        - com.slack.Slack
        - com.google.Chrome
        - one.ablaze.floorp
        - com.bitwarden.desktop
        - com.todoist.Todoist
        - org.ferdium.Ferdium
        - it.mijorus.gearlever
        - io.freetubeapp.FreeTube
        - dev.zed.Zed
        - com.usebruno.Bruno
        - com.logseq.Logseq
      remove: []
  - type: signing
