name: mars
description: This is my personal OS image.
base-image: ghcr.io/wayblueorg/qtile-nvidia-open
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /
  # - type: dnf
  #   remove:
  #     packages:
  #       - fish
  - type: dnf
    repos:
      copr:
        - atim/starship
        - atim/bottom
        - atim/lazygit
        - pgdev/ghostty
        - varlad/zellij
        - wezfurlong/wezterm-nightly
        - sneexy/zen-browser
        - atim/nushell
      files:
        - windsurf.repo
    group-install:
      packages:
        - cosmic-desktop-environment
    install:
      packages:
        - micro
        - starship
        - gh
        - xrandr
        # - fish
        # - xonsh
        - bottom
        # - alacritty
        # - ImageMagick
        # - mpv
        # - neovim
        - fontawesome-fonts
        # - tumbler
        - screen
        - direnv
        - langpacks-en
        - lazygit
        - pavucontrol
        # - python3-devel
        - dconf-editor
        # - cosmic-desktop
        - wezterm
        - windsurf
        - ghostty
        - zellij
        - zen-browser
        # - nushell
  - type: chezmoi
    repository: "https://github.com/robintully/dotfiles"
    all-users: true
    file-conflict-policy: replace
  - type: justfiles
    validate: false
    include:
      - kde.just
  - type: default-flatpaks
    notify: true
    user:
      repo-name: flathub
      repo-title: "Flathub (User)"
      install:
        - org.mozilla.firefox
        - org.libreoffice.LibreOffice
        - org.gustavoperedo.FontDownloader
        - com.github.tchx84.Flatseal
        - io.github.celluloid_player.Celluloid
        - io.beekeeperstudio.Studio
        - com.borgbase.Vorta
        - com.slack.Slack
        - com.google.Chrome
        - com.bitwarden.desktop
        - com.todoist.Todoist
        - org.ferdium.Ferdium
        - it.mijorus.gearlever
        - io.freetubeapp.FreeTube
        - dev.zed.Zed
        - com.usebruno.Bruno
        - com.logseq.Logseq
        - app.zen_browser.zen
        - com.vivaldi.Vivaldi
      remove: []
  - type: signing
