name: mars
description: This is my personal OS image.
base-image: ghcr.io/wayblue/hyprland-nvidia
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - >-
        https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - >-
        https://copr.fedorainfracloud.org/coprs/atim/bottom/repo/fedora-%OS_VERSION%/atim-bottom-fedora-%OS_VERSION%.repo
      - >-
        https://copr.fedorainfracloud.org/coprs/jplie/budgie-extras/repo/fedora-%OS_VERSION%/jplie-budgie-extras-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - rofi
      - fish
      - gh
      - xrandr
      - bottom
      - gnome-tweaks
      - alacritty
      - ImageMagick
      - mpv
      - neovim
      - fontawesome-fonts
      - tumbler
      - budgie-extras
      - screen
      - direnv
      - langpacks-en
      - ruff
      - uv
    remove:
      - firefox
      - firefox-langpacks
  - type: default-flatpaks
    notify: true
    system:
      install:
        - LibreOffice: org.libreoffice.LibreOffice
        - FontDownloader: org.gustavoperedo.FontDownloader
        - Flatseal: com.github.tchx84.Flatseal
        - Celluloid: io.github.celluloid_player.Celluloid
        - Obsidian: md.obsidian.Obsidian
        - Studio: io.beekeeperstudio.Studio
        - Vorta: com.borgbase.Vorta
        - Slack: com.slack.Slack
        - Chrome: com.google.Chrome
        - wezterm: org.wezfurlong.wezterm
        - Floorp: one.ablaze.floorp
        - Bitwarden: com.bitwarden.desktop
        - Todoist: com.todoist.Todoist
        - Ferdium: org.ferdium.Ferdium
        - Freetube: io.freetubeapp.FreeTube
        - Zed: dev.zed.Zed
      remove: null
  - type: chezmoi
    repository: 'https://github.com/robintully/dotfiles'
    all-users: true
    file-conflict-policy: replace
  - type: signing
